src/SDK/System/Api/Article.php, src/SDK/System/Api/Category.php, src/SDK/System/DTO/ArticleDTO.php, src/SDK/System/Service/ArticleInterface.php, src/SDK/System/Service/CategoryInterface.php
=> 资讯文章、文章分类相关

src/SDK/System/DTO/BankDTO.php, src/SDK/System/DTO/KeyDTO.php, src/SDK/System/DTO/ValueDTO.php, src/SDK/System/Exception/BankException.php, src/SDK/System/Exception/ValueException.php, src/SDK/System/Service/BankInterface.php, src/SDK/System/Service/KeyInterface.php, src/SDK/System/Service/ValueInterface.php
=> 系统模块相关代码优化提交

src/SDK/System/Service/ArticleInterface.php
=> 修改文章interface

src/SDK/System/DTO/GbDTO.php, src/SDK/System/Exception/GbException.php, src/SDK/System/Service/GbInterface.php
=> 系统字典--网格化区域信息

src/SDK/Service/Api/Contract.php, src/SDK/Service/DTO/ContractDTO.php, src/SDK/Service/Exception/ContractException.php, src/SDK/Service/Service/CompanyInterface.php, src/SDK/Service/Service/ContractInterface.php, src/SDK/System/Service/ArticleInterface.php, src/SDK/System/Service/CategoryInterface.php
=> 新增合同版本相关，修改企业相关注解

src/SDK/Service/Api/ContractNumber.php, src/SDK/Service/Exception/CompanyException.php, src/SDK/Service/Exception/ContractException.php, src/SDK/Service/Exception/ContractNumberException.php, src/SDK/Service/Service/CompanyInterface.php, src/SDK/Service/Service/ContractInterface.php, src/SDK/Service/Service/ContractNumberInterface.php, src/SDK/System/Service/ArticleInterface.php, src/SDK/System/Service/CategoryInterface.php
=> 新增合同编号相关，去除 interface的注解验证

src/SDK/Service/Api/ContractUser.php, src/SDK/Service/DTO/ContractUserDTO.php, src/SDK/Service/Exception/ContractUserException.php, src/SDK/Service/Service/ContractUserInterface.php
=> 用户合同签订记录相关

src/SDK/System/Service/FeedbackInterface.php, src/SDK/User/DTO/UserAddressDTO.php, src/SDK/User/Service/AddressInterface.php
=> 用户地址 && 反馈修改

src/SDK/System/Api/Article.php, src/SDK/System/Service/ArticleInterface.php
=> 系统模块 新增登录用户信息

src/SDK/Service/Api/EntityCustom.php, src/SDK/Service/DTO/EntityCustomDTO.php, src/SDK/Service/Exception/EntityCustomException.php, src/SDK/Service/Service/EntityCustomInterface.php
service模块 新增店铺实体认证自定义商圈市场楼层信息相关
=> service模块 新增店铺实体认证自定义商圈市场楼层信息相关

src/SDK/Service/Api/Entity.php, src/SDK/Service/DTO/EntityCustomDTO.php, src/SDK/Service/DTO/EntityDTO.php, src/SDK/Service/Exception/EntityException.php, src/SDK/Service/Service/EntityInterface.php
=> service模块-新增店铺实体认证相关

src/SDK/Service/Api/Seller.php, src/SDK/Service/DTO/SellerDTO.php, src/SDK/Service/Exception/SellerException.php, src/SDK/Service/Service/SellerInterface.php
=> service模块 新增店铺卖家认证相关

src/SDK/Service/Api/Brand.php, src/SDK/Service/DTO/BrandDTO.php, src/SDK/Service/Exception/BrandException.php, src/SDK/Service/Service/BrandInterface.php, src/SDK/Service/Service/ContractInterface.php, src/SDK/Service/Service/EntityInterface.php, src/SDK/Service/Service/SellerInterface.php
=> service模块 新增店铺品牌认证相关

src/SDK/Service/Api/Contract.php, src/SDK/Service/Api/Service.php, src/SDK/Service/DTO/ServiceDTO.php, src/SDK/Service/Exception/ContractException.php, src/SDK/Service/Service/ContractInterface.php, src/SDK/Service/Service/ServiceInterface.php
=> service模块 新增增值服务相关

src/Exception/LogicException.php, src/SDK/Service/Api/Lists.php, src/SDK/Service/Api/Service.php, src/SDK/Service/DTO/ListsDTO.php, src/SDK/Service/DTO/ServiceDTO.php, src/SDK/Service/Exception/BrandException.php, src/SDK/Service/Exception/BuyException.php, src/SDK/Service/Exception/CompanyException.php, src/SDK/Service/Exception/ContractException.php, src/SDK/Service/Exception/ContractNumberException.php, src/SDK/Service/Exception/ContractUserException.php, src/SDK/Service/Exception/EntityCustomException.php, src/SDK/Service/Exception/EntityException.php, src/SDK/Service/Exception/ListsException.php, src/SDK/Service/Exception/SellerException.php, src/SDK/Service/Exception/ServiceException.php, src/SDK/Service/Service/ListsInterface.php, src/SDK/Service/Service/ServiceInterface.php
service模块 新增增值服务清单相关和统一修改exception
=> service模块 新增增值服务清单相关和统一修改exception

src/SDK/Service/Api/Buy.php, src/SDK/Service/Api/Company.php, src/SDK/Service/DTO/BrandDTO.php, src/SDK/Service/DTO/BuyDTO.php, src/SDK/Service/DTO/CompanyDTO.php, src/SDK/Service/DTO/EntityDTO.php, src/SDK/Service/DTO/SellerDTO.php, src/SDK/Service/Service/BrandInterface.php, src/SDK/Service/Service/BuyInterface.php, src/SDK/Service/Service/CompanyInterface.php, src/SDK/Service/Service/EntityInterface.php, src/SDK/Service/Service/SellerInterface.php
=> service模块 新增服务购买记录相关

src/SDK/EellyClient.php, src/SDK/Service/Api/Buy.php, src/SDK/Service/Service/BuyInterface.php
=> service模块 移除:更新服务到期时间接口

src/SDK/System/Api/Article.php, src/SDK/System/Api/Category.php, src/SDK/System/Service/ArticleInterface.php, src/SDK/System/Service/CategoryInterface.php
=> 系统模块 修改文章和分类的字段

src/SDK/System/Api/Content.php, src/SDK/System/Api/Image.php, src/SDK/System/DTO/ContentDTO.php, src/SDK/System/DTO/ImageDTO.php, src/SDK/System/Service/CategoryInterface.php, src/SDK/System/Service/ContentInterface.php, src/SDK/System/Service/ImageInterface.php
=> 系统模块 调整文章相关接口

src/SDK/System/DTO/ArticleDTO.php, src/SDK/System/Service/ArticleInterface.php
=> 系统模块 调整文章详情字段

src/SDK/User/DTO/EntranceDTO.php, src/SDK/User/Exception/EntranceException.php, src/SDK/User/Service/BindInterface.php, src/SDK/User/Service/EntranceInterface.php
=> 用户模块-entrance

src/SDK/Service/Api/Contract.php, src/SDK/Service/Api/ContractNumber.php, src/SDK/Service/Api/EntityCustom.php, src/SDK/Service/DTO/ContractNumberDTO.php, src/SDK/Service/Service/BrandInterface.php, src/SDK/Service/Service/CompanyInterface.php, src/SDK/Service/Service/ContractInterface.php, src/SDK/Service/Service/ContractNumberInterface.php, src/SDK/Service/Service/ContractUserInterface.php, src/SDK/Service/Service/EntityCustomInterface.php, src/SDK/Service/Service/EntityInterface.php, src/SDK/Service/Service/SellerInterface.php
=> service模块 调整service相关接口

src/SDK/System/DTO/CommentReplyDTO.php, src/SDK/System/Service/CommentReplyInterface.php
=> 系统模块，表结构修改

src/SDK/System/Service/CategoryInterface.php
=> 系统模块 调整文章分类相关

src/SDK/System/Api/Bank.php, src/SDK/System/Api/Category.php, src/SDK/System/Api/Comment.php, src/SDK/System/DTO/DistrictStatisticsDTO.php, src/SDK/System/Service/BankInterface.php, src/SDK/System/Service/CommentInterface.php, src/SDK/System/Service/DistrictInterface.php, src/SDK/System/Service/DistrictStatisticsInterface.php, src/SDK/System/Service/MarketInterface.php, src/SDK/System/Service/ParamInterface.php, src/SDK/System/Service/ParamValueInterface.php, src/SDK/System/Service/RegionInterface.php
=> 系统模块，表结构修改优化

src/SDK/System/Api/ArticleCategory.php, src/SDK/System/Api/ArticleContent.php, src/SDK/System/Api/ArticleImage.php, src/SDK/System/DTO/ArticleCategoryDTO.php, src/SDK/System/DTO/ArticleContentDTO.php, src/SDK/System/DTO/ArticleImageDTO.php, src/SDK/System/Service/ArticleCategoryInterface.php, src/SDK/System/Service/ArticleContentInterface.php, src/SDK/System/Service/ArticleImageInterface.php
=> 系统模块 修改文章相关的文件名、类名

src/SDK/Data/Api/Summary.php, src/SDK/Data/Api/SummaryDay.php, src/SDK/Data/Api/SummaryDimension.php, src/SDK/Data/Service/SummaryDayInterface.php, src/SDK/Data/Service/SummaryDimensionInterface.php, src/SDK/Data/Service/SummaryInterface.php
=> data模块 新增data模块

src/SDK/Data/Api/EaTrack.php, src/SDK/Data/Service/EaTrackInterface.php
=> data模块 新增ea相关

src/SDK/Data/Api/EaTrack.php, src/SDK/Data/Exception/EaTrackException.php, src/SDK/Data/Service/EaTrackInterface.php
=> data模块 修改ea相关参数

src/SDK/Goods/Api/Category.php, src/SDK/Goods/Api/CategoryCustom.php, src/SDK/Goods/Api/Description.php, src/SDK/Goods/Api/Extend.php, src/SDK/Goods/Api/Favorite.php, src/SDK/Goods/Api/Goods.php, src/SDK/Goods/Api/Image.php, src/SDK/Goods/Api/Level.php, src/SDK/Goods/Api/Packet.php, src/SDK/Goods/Api/Price.php, src/SDK/Goods/Api/Property.php, src/SDK/Goods/Api/PropertyCategoryKey.php, src/SDK/Goods/Api/PropertyCategoryVal.php, src/SDK/Goods/Api/PropertyKey.php, src/SDK/Goods/Api/PropertyValue.php, src/SDK/Goods/Api/PropertyValueCustom.php, src/SDK/Goods/Api/Spec.php, src/SDK/Goods/Api/Unit.php, src/SDK/Goods/Api/Video.php, src/SDK/Goods/Api/Weight.php, src/SDK/Goods/Api/WeightItem.php, src/SDK/Goods/Service/GoodsInterface.php
=> 商品模块 重新生成api文件

src/SDK/Store/Api/Store.php, src/SDK/Store/Service/StoreInterface.php
=> 店铺模块 新增店铺列表接口

src/DTO/AbstractDTO.php, src/DocsBundle/Adapter/AbstractDocumentShow.php, src/DocsBundle/ApiDocLogic.php, src/DocsBundle/DocsBundle.php, src/Psr4Autoloader.php, src/SDK/EellyClient.php, src/SDK/Example/Api/Benchmark.php, src/SDK/Example/Api/Params.php, src/SDK/Example/Service/BenchmarkInterface.php, src/SDK/User/Api/Address.php, src/SDK/User/Api/Auth.php, src/SDK/User/Api/AuthCallback.php, src/SDK/User/Api/Bind.php, src/SDK/User/Api/Entrance.php, src/SDK/User/Api/Extend.php, src/SDK/User/Api/Grade.php, src/SDK/User/Api/Score.php, src/SDK/User/Api/Security.php, src/SDK/User/Api/Status.php, src/SDK/User/Api/Tag.php, src/SDK/User/Api/User.php, src/SDK/User/DTO/SecurityDTO.php, src/SDK/User/Service/AddressInterface.php, src/SDK/User/Service/AuthCallbackInterface.php, src/SDK/User/Service/AuthInterface.php, src/SDK/User/Service/SecurityInterface.php, src/SDK/User/Service/UserInterface.php
Eelly Client 改用 Shadon Client
benchmark interface add echo method
=> fix code style

src/SDK/Order/Api/SellerOrder.php
=> 小程序2期开发，获取订单数据Api的bug修复

src/SDK/Live/Api/LiveShare.php, src/SDK/Live/Service/LiveShareInterface.php
=> 更改反馈参数，不需要user

src/SDK/Live/Api/LiveShare.php, src/SDK/Live/Service/LiveShareInterface.php
=> 直播间分享添加活动id和客户端信息

src/SDK/Live/Api/LivePlan.php, src/SDK/Live/Service/LiveActivityInterface.php, src/SDK/Live/Service/LiveInterface.php, src/SDK/Live/Service/LivePlanInterface.php, src/SDK/Order/Api/SellerOrder.php, src/SDK/Order/Service/SellerOrderInterface.php
=> 合并代码到develop

src/SDK/Message/Api/AlySms.php, src/SDK/Message/Service/AlySmsInterface.php
=> 短信展示模版返回值修改

src/SDK/Message/Api/AlySms.php, src/SDK/Message/Service/AlySmsInterface.php
=> 注解returnExample报错解决

src/SDK/Order/Api/BuyerOrder.php, src/SDK/Order/Service/BuyerOrderInterface.php
=> 新增修改退货退款接口和修改注释

src/SDK/Order/Api/Like.php, src/SDK/Order/Service/LikeInterface.php
=> 商品增加自定义点赞数控制

src/SDK/Order/Api/Order.php, src/SDK/Order/Service/OrderInterface.php
(cherry picked from commit 66d8fefa7067a4dab2697c1b2cd39ffa5c545a83)
=> 增加app消息商品信息查询接口

src/SDK/User/Api/User.php, src/SDK/User/Service/UserInterface.php
This reverts commit d4abb0c2e9b5eefeee54456eba055ea1172d438f.
=> Revert "test环境报错修复"

src/SDK/Order/Api/Order.php, src/SDK/Order/Service/OrderInterface.php, src/SDK/Pay/Api/Refund.php, src/SDK/Pay/Service/RefundInterface.php
=> 新增获取订单信息接口

src/SDK/EellyOldCode/Api/Store/Store.php, src/SDK/Live/Api/LabelManage.php, src/SDK/Live/Service/LabelManageInterface.php, src/SDK/User/DTO/ExtendDTO.php
=> 后台直播中心标签、客服微信号
